# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pb.reverse_pb2 as reverse__pb2


class ReverseServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ReverseString = channel.unary_unary(
        '/reverse.ReverseService/ReverseString',
        request_serializer=reverse__pb2.ReverseRequest.SerializeToString,
        response_deserializer=reverse__pb2.ReverseReply.FromString,
        )


class ReverseServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ReverseString(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReverseServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ReverseString': grpc.unary_unary_rpc_method_handler(
          servicer.ReverseString,
          request_deserializer=reverse__pb2.ReverseRequest.FromString,
          response_serializer=reverse__pb2.ReverseReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'reverse.ReverseService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
