# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reverse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reverse.proto',
  package='reverse',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rreverse.proto\x12\x07reverse\"\x1e\n\x0eReverseRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\" \n\x0cReverseReply\x12\x10\n\x08reversed\x18\x02 \x01(\t2S\n\x0eReverseService\x12\x41\n\rReverseString\x12\x17.reverse.ReverseRequest\x1a\x15.reverse.ReverseReply\"\x00\x62\x06proto3')
)




_REVERSEREQUEST = _descriptor.Descriptor(
  name='ReverseRequest',
  full_name='reverse.ReverseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='reverse.ReverseRequest.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=56,
)


_REVERSEREPLY = _descriptor.Descriptor(
  name='ReverseReply',
  full_name='reverse.ReverseReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reversed', full_name='reverse.ReverseReply.reversed', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['ReverseRequest'] = _REVERSEREQUEST
DESCRIPTOR.message_types_by_name['ReverseReply'] = _REVERSEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReverseRequest = _reflection.GeneratedProtocolMessageType('ReverseRequest', (_message.Message,), {
  'DESCRIPTOR' : _REVERSEREQUEST,
  '__module__' : 'reverse_pb2'
  # @@protoc_insertion_point(class_scope:reverse.ReverseRequest)
  })
_sym_db.RegisterMessage(ReverseRequest)

ReverseReply = _reflection.GeneratedProtocolMessageType('ReverseReply', (_message.Message,), {
  'DESCRIPTOR' : _REVERSEREPLY,
  '__module__' : 'reverse_pb2'
  # @@protoc_insertion_point(class_scope:reverse.ReverseReply)
  })
_sym_db.RegisterMessage(ReverseReply)



_REVERSESERVICE = _descriptor.ServiceDescriptor(
  name='ReverseService',
  full_name='reverse.ReverseService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=92,
  serialized_end=175,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReverseString',
    full_name='reverse.ReverseService.ReverseString',
    index=0,
    containing_service=None,
    input_type=_REVERSEREQUEST,
    output_type=_REVERSEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REVERSESERVICE)

DESCRIPTOR.services_by_name['ReverseService'] = _REVERSESERVICE

# @@protoc_insertion_point(module_scope)
